CREATE TABLE IF NOT EXISTS mws_sed_fdoc_users (
     ID INT UNSIGNED NOT NULL,
     BASE VARCHAR(255) DEFAULT NULL,
    --
    PRIMARY KEY (ID)
    );
CREATE TABLE IF NOT EXISTS mws_sed_fdoc_send (
        `ID` INT  NOT NULL AUTO_INCREMENT,
        `ENTITY_ID` INT  NOT NULL,
        `DEAL_ID` INT  NOT NULL,
        `COMPANY_ID` INT NOT NULL,
        `USER_ID` INT,
        `SEND_ID` VARCHAR(255) NOT NULL,
        `PACKAGE_URL` VARCHAR(255),
        `TYPE_SEND` VARCHAR(255),
        `DOC_NAME` VARCHAR(255),
        `STATUS` VARCHAR(255),
        `DATE_CREATE` DATETIME,
        PRIMARY KEY (`ID`)
    
);